spring.application.name=ilena-backend
server.port=8000

# Logging
logging.level.root=INFO
logging.level.com.ilena.backend=DEBUG

# API Documentation
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

